version: "3"
services:
  kettle_scheduler_mysql:
    image: mysql:latest
    container_name: mysqldb
    volumes:
      #- ./data/mysql/datadir:/var/lib/mysql
      - ./config/mysql/mysql.cnf:/etc/my.cnf
      - ./data/mysql/source:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "TZ=Asia/Shanghai"
    networks: #加入指定网络
      - elk

networks:
  elk:
    driver: bridge
