version: "3"
services:
  kettle_scheduler_web:
    image: opsu/kettle-scheduler:1.2
    container_name: kettle_scheduler_web
    volumes:
      - ./config/resource:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/resource
      - ./config/tomecat/conf:/usr/local/tomcat/conf
      - ./data/sqlite/kettle-sqlite.db:/usr/local/tomcat/kettle-sqlite.db
      - ./driver/mysql-connector-java-5.1.48.jar:/usr/local/tomcat/data-integration/lib/mysql-connector-java-5.1.48.jar
      - ./driver/sqlite-jdbc-3.7.2.jar:/usr/local/tomcat/data-integration/lib/sqlite-jdbc-3.7.2.jar
    ports:
      - "8080:8080"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: #加入指定网络
      - elk
networks:
  elk:
    driver: bridge
