version: "3"
services:
  kettle_scheduler_web:
    image: opsu/kettle-scheduler:1.2
    container_name: kettle_scheduler_web
    links:
      - "kettle_scheduler_mysql:kettle_scheduler_mysql"
    volumes:
      - ./config/resource:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/resource
      - ./config/tomecat/conf:/usr/local/tomcat/conf
    ports:
      - "8080:8080"
    depends_on:
      - kettle_scheduler_mysql
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: #加入指定网络
      - elk
  kettle_scheduler_mysql:
    image: mysql:latest
    container_name: kettle_scheduler_mysql
    volumes:
      #- ./data/mysql/datadir:/var/lib/mysql
      - ./config/mysql/mysql.cnf:/etc/my.cnf
      - ./data/mysql/source:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "TZ=Asia/Shanghai"
    networks: #加入指定网络
      - elk

networks:
  elk:
    driver: bridge
